<form method="POST" class="form">
  <div class="forceColor"></div>
  <div class="topbar">
    <div class="spanColor"></div>
		<input name="login" class="input" type="text" id="login" placeholder="Login"/>
		<input type="password" class="input" name="password" id="password" placeholder="Mot de passe" />
		<input type="password" class="input" name="confirm" id="confirm" placeholder="Confirmation du mot de passe"/>
  </div>
  <button class="submit" id="submit" name="action" value="login">Cr&eacute;er un compte</button>
  <center>
</br>
</br>
</br>
	<p style="color: #fff;font-size: 16px;">Vous avez déja un compte ?</p>
</br>
	<button type="submit" class="submit" name="action" value="login"><a href="login" class="aCreerCompte">Se connecter</a></button>
	</center>
</form>