<!-- <form method="POST" enctype="multipart/form-data">
	<fieldset>
		<legend>Cr&eacute;er votre compte</legend>
		<div class="form-group">
			<label for="login">Login :</label>
			<input name="login" type="text" id="login" />
		</div>
		<div class="form-group">
			<label for="hash">Mot de Passe :</label>
			<input type="password" name="hash" id="hash" />
		</div>
		<div class="form-group">
			<label for="confirm">Confirmer le mot de passe :</label>
			<input type="password" name="confirm" id="confirm" />
		</div>
	</fieldset>
			<p><button type="submit" class="btn btn-default" name="action" value="create">S'enregistrer</button></p>
</form>
 -->
<div class="form" method="POST">
  <div class="forceColor"></div>
  <div class="topbar">
    <div class="spanColor"></div>
		<input name="login" class="input" type="text" id="login" placeholder="Login"/>
		<input type="password" class="input" name="password" id="password" placeholder="Mot de passe" />
		<input type="password" class="input" name="confirm" id="confirm" placeholder="Confirmation du mot de passe"/>
  </div>
  <button class="submit" id="submit" name="action" value="login">Cr&eacute;er un compte</button>
</div>