<header>
	<nav class="navbar navbar-default">
		<ul class="nav navbar-nav">
			<li class="active"><a href="tchat">Votre tchat</a></li>
		</ul>
		<ul class="nav navbar-nav navbar-right">
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><?=$_SESSION['login']?> <span class="caret"></span></a>
				<ul class="dropdown-menu">
					<li><a href="monCompte">Mon compte</a></li>
				</ul>
			</li>
			<li><a href="logout">Logout</a></li>
		</ul>
</header>