<header>
	<nav class="navbar">
		<ul class="nav navbar-nav">
			<li><a href="tchat" class="nav">Votre tchat</a></li>
			<li><a href="gestion_user" class="nav">Gestion users</a></li>
			<li><a href="gestion_message" class="nav">Gestion messages</a></li>
		</ul>
		<ul class="nav navbar-nav navbar-right">
			<li class="dropdown">
				<a href="#" class="nav" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><?=$currentUser->getLogin()?> <div class="caret"></div></a>
				<ul class="dropdown-menu input">
					<li><a href="monCompte" class="nav" >Mon compte</a></li>
				</ul>
			</li>
			<li><a href="logout" class="nav">Logout</a></li>
		</ul>
</header>