<header>
	<nav class="navbar">
		<ul class="nav navbar-nav">
			<li><a href="tchat" class="nav">Votre tchat</a></li>
		</ul>
		<ul class="nav navbar-nav navbar-right">
			<li class="dropdown">
				<a href="#" class="nav" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><?=$_SESSION['login']?> <span class="caret"></span></a>
				<ul class="dropdown-menu">
					<li><a href="monCompte" class="nav" >Mon compte</a></li>
				</ul>
			</li>
			<li><a href="logout" class="nav">Logout</a></li>
		</ul>
</header>