<header>
	<nav class="navbar navbar-default">
		<ul class="nav navbar-nav">
			<li class="active"><a href="listCom">Comptes</a></li>
		</ul>
		<ul class="nav navbar-nav navbar-right">
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><?=$_SESSION['login']?> <span class="caret"></span></a>
			</li>
		</ul>
		<ul class="nav navbar-nav navbar-right">
			<li><a href="logout">Logout</a></li>
		</ul>
</header>