<form method="POST" class="form">
  <div class="forceColor">
  <div class="topbar">
    <div class="spanColor">
		<input name="login" class="input" type="text" id="login" placeholder="Login"/>
		<input type="password" class="input" name="password" id="password" placeholder="Password" />
  </div>
  <button type="submit" class="submit" name="action" value="login">Se connecter</button>
</br>
	<center>
		<p style="color: #fff;font-size: 18px;">ou
</br>
</br>
		<button class="submit" id="submit" name="action"><a href="create" class="aCreerCompte">Cr&eacute;er un compte</a></p></button>
	</center>
</br>
</div>
</div>
</form> 