<!-- <p>Veuillez vous connecter pour tchater.</p>
<form method="POST">
	<fieldset>
		<legend>Connexion</legend>
		<p>
			<label for="login">Login :</label>
			<input name="login" type="text" id="login" />
		<br />
			<label for="password">Password :</label>
			<input type="password" name="password" id="password" />
		</p>
	</fieldset>
		<p><button type="submit" class="btn btn-default" name="action" value="login">OK</button></p>
</form> -->

<form method="POST" class="form">
  <div class="forceColor"></div>
  <div class="topbar">
    <div class="spanColor"></div>
		<input name="login" class="input" type="text" id="login" placeholder="Login"/>
		<input type="password" class="input" name="password" id="password" placeholder="Password" />
  </div>
  <button type="submit" class="submit" name="action" value="login">Se connecter</button>
</br>
	<center>
		<p style="color: #fff;font-size: 20px;">ou
</br>
</br>
		<button class="submit" id="submit" name="action"><a href="create">Cr&eacute;er un compte</a></p></button>
	</center>
</br>
</form> 