<form method="POST" class="form">
  <div class="forceColor"></div>
  <div class="topbar">
    <div class="spanColor"></div>
		<input name="login" class="input" type="text" id="login" placeholder="Login" style="font-size: 18px" required/>
		<input type="password" class="input" name="password" id="password" placeholder="Password" required/>
  </div>
  <button type="submit" class="submit" name="action" value="login">Se connecter</button>
</br>
	<center>
		<p style="color: #fff;font-size: 18px;">ou
</br>
</br>
		<button class="submit" id="submit" name="action"><a href="create" class="aCreerCompte">Cr&eacute;er un compte</a></p></button>
	</center>
</br>
</div>
</form> 