<form method="POST" class="form" enctype="multipart/form-data">
	<div class="forceColor"></div>
		<div class="topbar">
		<legend>Modifier votre compte</legend>
		<div class="spanColor"></div>
			<input name="login" class="input" type="text" id="login" value="<?=htmlentities($_SESSION['login'])?>" placeholder="Login" style="font-size: 18px"/>
			<input type="password" class="input" name="oldPassword" id="password" placeholder="Ancien mot de passe" required/>
			<input type="password" class="input" name="newPassword1" id="password2" placeholder="Nouveau mot de passe" required/>
			<input type="password" class="input" name="newPassword2" id="confirm" placeholder="Confirmation du mot de passe" required />
		</div>
	<center>
		<button type="submit" class="submit" name="action" value="modifPw">Modifier</button>
	</center>
</form>