<form method="POST" enctype="multipart/form-data">
	<fieldset>
		<legend>Modifier votre compte</legend>
			<form method="POST" enctype="multipart/form-data">
				<fieldset>

					
					<div class="form-group">
						<label for="password">Ancien mot de passe :</label>
						<input type="password" name="password" id="password" required />
					</div>
					<div class="form-group">
						<label for="login">Login :</label>
						<input name="login" type="text" id="login" value="<?=htmlentities($client['login'])?>"required/>
					</div>
					<div class="form-group">
						<label for="password"> Nouveau mot de passe :</label>
						<input type="password" name="password" id="password" required/>
					</div>
					<div class="form-group">
						<label for="confirm">Confirmer le nouveau mot de passe :</label>
						<input type="password" name="confirm" id="confirm" required/>
					</div>
					
				</fieldset>
						<p><button type="submit" class="btn btn-default" name="action" value="modifPw">Modifier</button></p>
			</form>