<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <!--[if IE]>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <![endif]-->
    <title>Votre tchat</title>
    <!-- BOOTSTRAP CORE STYLE CSS -->
    <link href="assets/css/bootstrap.css" rel="stylesheet" />

</head>
<body style="font-family:Verdana">
  <div class="container">
<div class="row " style="padding-top:40px;">
    <br /><br />
    <div class="col-md-4">
      <div class="panel panel-primary">
        <div class="panel-heading">
           UTILISATEURS
        </div>
        <div class="panel-body">
            <ul class="media-list">
                <li class="media">
                    <div class="media-body">
                        <div class="media"> 
                            <div class="media-body" >
                                <h5>Login user </h5>
                               <small class="text-muted">Active From 3 hours</small>
                            </div>
                        </div>
                    </div>
                </li>                    
        	</ul>
        </div>
      </div>
    </div>
    <div class="col-md-8">
        <div class="panel panel-info">
            <div class="panel-heading">
                TITRE
            </div>
            <div class="panel-body">
<ul class="media-list">

                                    <li class="media">

                                        <div class="media-body">

                                            <div class="media">

                                                <div class="media-body" >
                                                    TEXTE MESSAGE
                                                    <br />
                                                   <small class="text-muted">login user | date</small>
                                                    <hr />
                                                </div>
                                            </div>

                                        </div>
                                    </li>
     
     
     
                                </ul>
            </div>
            <div class="panel-footer">
                <div class="input-group">
                                    <input type="text" class="form-control" placeholder="Enter Message" />
                                    <span class="input-group-btn">
                                        <button class="btn btn-info" type="button">SEND</button>
                                    </span>
                                </div>
            </div>
        </div>
    </div>
</div>
</div>
</body>
</html>

